version: '3'
services:
  api:
    container_name: api-softdough
    restart: always
    build: .
    ports:
      - "5555:8080"
    environment:
      - PORT=8080
      - DATABASE_HOST=147.50.230.32
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=softdough@db
      - DATABASE_NAME=softdoughdb
      - FRONT=http://softdough-front-end:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge